language: node_js
node_js:
  - "8"
sudo: false

before_install:
  - npm install phantomjs
  - rvm install 2.2
  - rvm use 2.2
  - gem install hiptest-publisher
  - hiptest-publisher -c javascript-qunit.conf --token=$SECRET_TOKEN --only=tests --test-run-id=1966

script:
  - node_modules/node-qunit-phantomjs/bin/node-qunit-phantomjs ./tests/index.html --verbose --timeout=10 | tee /dev/stderr | grep '^<' > qunit-junit-report.xml

after_script:
  - hiptest-publisher -c javascript-qunit.conf --token=$SECRET_TOKEN --push=qunit-junit-report.xml --test-run-id=1966

notifications:
  webhooks:
    urls:
      - https://hiptest.net/report_global_failure/$SECRET_TOKEN/1966/
    on_success: never
    on_failure: never
    on_start: never
    on_error: always
