language: node_js
sudo: false

before_install:
  - rvm install 2.2
  - rvm use 2.2
  - gem install hiptest-publisher
  - hiptest-publisher -c javascript-qunit.conf --only=tests --test-run-id=1966

script:
  - grunt qunit

after_script:
  - hiptest-publisher -c javascript-qunit.conf --push=_build/test-reports/TEST-index.xml --test-run-id=1966
